// E-Book Librarian - OpenSCAD Enclosure Template
//
// This script provides a template for creating a custom, book-shaped
// enclosure for the E-Book Librarian project.
//
// How to Use:
// 1. Install OpenSCAD from https://openscad.org/
// 2. Open this file in the OpenSCAD editor.
// 3. Modify the variables in the "Configuration" section.
// 4. To see the final assembled book, set `build_mode = "assembly"`.
// 5. To see the parts separated for 3D printing, set `build_mode = "parts"`.
// 6. Press F5 to preview, F6 to render, then export the STL.

// --- Configuration ---

// --- Build Mode ---
// "assembly": Shows the final assembled product.
// "parts":    Shows the book box and cover laid out flat for printing.
build_mode = "assembly"; // ["assembly", "parts"]

// --- Internal Dimensions ---
// Measure your assembled electronics and add some tolerance.
interior_width = 80;  // (mm)
interior_depth = 120; // (mm)
interior_height = 25; // (mm)

// --- Book Dimensions ---
wall_thickness = 3;   // Thickness of the book's walls
cover_overhang = 5;   // How much the "cover" extends beyond the "pages"
spine_radius = 5;     // The rounding of the book's spine

// --- Lithophane Files (Optional) ---
// These files are expected to be generated by other scripts.
// The `bent_litho_stl_path` is created by the `bend_mesh.py` Blender script.
bent_litho_stl_path = "bent_litho.stl";
litho_enabled = true; // Set to true to include the lithophane in the assembly


// --- Helper variables (do not modify) ---
outer_width = interior_width + (wall_thickness * 2);
outer_depth = interior_depth + (wall_thickness * 2);
outer_height = interior_height + wall_thickness; // Bottom wall only

cover_width = outer_width + (cover_overhang * 2);
cover_depth = outer_depth + cover_overhang; // Overhang on front edge
cover_height = wall_thickness;


// --- Main Execution Logic ---

if (build_mode == "assembly") {
    final_assembly();
} else {
    // Lay out parts flat for printing
    book_box();
    translate([cover_width + 10, 0, 0]) {
        cover();
    }
}


// --- Component Modules ---

module final_assembly() {
    // This module assembles all the parts into the final product.

    // 1. The main box
    book_box();

    // 2. The cover, placed on top of the box
    translate([0, 0, outer_height]) {
        cover();
    }

    // 3. The bent lithophane, placed on top of the cover
    if (litho_enabled) {
        // You will likely need to adjust the translation and rotation
        // to get the perfect fit for your specific lithophane.
        translate([cover_overhang, -cover_overhang, outer_height + cover_height]) {
            // Rotate the lithophane to be flat on the cover
            rotate([90, 0, 90]) {
                import(bent_litho_stl_path);
            }
        }
    }
}

module book_box() {
    difference() {
        book_block(outer_width, outer_depth, outer_height, spine_radius);
        translate([wall_thickness, wall_thickness, wall_thickness]) {
            cube([interior_width, interior_depth, interior_height + 1]); // +1 to ensure it cuts through
        }
    }
}

module cover() {
    difference() {
        book_block(cover_width, cover_depth, cover_height, spine_radius + cover_overhang);
        translate([cover_overhang, cover_overhang, -1]) {
             book_block(outer_width, outer_depth, cover_height + 2, spine_radius);
        }
    }
}

module book_block(width, depth, height, radius) {
    hull() {
        cube([width - radius, depth, height]);
        translate([width - radius, 0, 0]) {
            cylinder(h=height, r=radius, $fn=100);
        }
    }
}
